goForward(100)
console.log(_position)
turnLeft()
goForward(100)
console.log(_position)
turnRight()
goForward(100)
console.log(_position)
turnLeft()
goForward(100)
turnLeft()
goForward(100)
turnRight()

console.log(_heading)